### ISSUE TITLE
При стрельбе из лука

### ISSUE THREAD

**Issue by LuxArcid** [kentovka/ArcCW#1]
[arrcw_baza] addons/arrcw_baza/lua/weapons/arccw_base/sh_firing.lua:175: attempt to perform arithmetic on a table value
  1. PrimaryAttack - addons/arrcw_baza/lua/weapons/arccw_base/sh_firing.lua:175
   2. unknown - addons/arrcw_baza/lua/weapons/arccw_base/sh_think.lua:134

**Comment by bydlocodd** [comment]
Probably fixed with [a7eb826](https://github.com/kentovka/ArcCW/commit/a7eb826a5fa1d4d1fe93eeca27f6633978dfd077)
